formatter: markdown table

sections:
  show:
    - header
    - inputs
    - modules
    - footer

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    # GCP Infra

    {{ .Content }}

    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true