apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
# frontend - delete frontend-external service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: frontend-external
    $patch: delete